### ISSUE TITLE
[Enhancement]  add ability to add nitro reaction and delete webhook message using reaction

### ISSUE THREAD

**Issue by SeasonPhan** [Willy-JL/animate-my-emojis#2]

**Comment by WillyJL** [comment]
Yes that is a very good idea, I never even thought about it but yeah you can't delete your own messages right now... I'll make it temporary so you only have like 5 minutes to delete it though

**Comment by WillyJL** [comment]
Added!

**Comment by SeasonPhan** [comment]
Nice 🐳
It would be nice to have a way to delete the message at any time but this is better than nothing

**Comment by WillyJL** [comment]
Unfortunately being able to delete it anytime would need some kind of message id storage so it's not practical when running on heroku :/

**Comment by SeasonPhan** [comment]
oh i see
